<!-- Include Alert Message here, better than showing it in the layout to more easily control css -->
@include('row-alert')

<div class="row">
    <div class="container">
        <div class="jumbotron">
            <h2>Laravel 2FA Demo with MySQL, Redis & Google Authenticator</h2>
            <p>
                This example illustrates how Two-factor authentication can be integrated on a freshly baked Laravel
                application. As you may know already, Two-factor authentication greatly improves the security of any
                web/mobile application. We will go through account registration, login, and Two-factor authentication
                processes in this example.
            </p>
            <p>
                Github: {{ HTML::link('https://github.com/gossspel/laravel_2fa_demo', 'gossspel/laravel_2fa_demo') }}<br>
                Author: {{ HTML::link('https://www.linkedin.com/pub/sunny-chan/23/a26/1a1', 'Sunny Chan') }}
                (Founder of {{ HTML::link('https://www.crypteon.net', 'Crypteon.Net') }})<br>
                Credits: Laravel Team for {{ HTML::link('http://laravel.com', 'Laravel') }},
                Abdulrhman Alkhodiry for {{ HTML::link('https://github.com/zeroows/Laravel-OTPass-Bundle', 'OTPass') }}
            </p>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    STEP 1 - Register
                </h3>
            </div>
            <div class="panel-body">
                This is easy, simply click on the "Register" link in the upper right corner. Fill out the form and
                click on the "Register" button. You will see some form validation errors if your inputs aren't good
                enough.
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    STEP 2 - Login
                </h3>
            </div>
            <div class="panel-body">
                This is just as easy as STEP 1, simply click on the "Login" link in the upper right corner. Again fill
                out the form and click on the "Login" button.
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    STEP 3 - Turn on Two-factor Authentication
                </h3>
            </div>
            <div class="panel-body">
                After logging in, you will be redirected to the Account Setting page. Follow the instruction there to
                turn on Two-factor Authentication. Note that you will need a smartphone that runs on one of the
                following operating system: iOS, Android, Windows Phone.
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    STEP 4 - Test out Two-factor Authentication
                </h3>
            </div>
            <div class="panel-body">
                Log out and then log in again. The system will require you to enter the 6 digits code generated by
                Google Authenticator. Simply open the Google Authenticator app on your smart phone and enter the 6
                digits code tied to the Laravel2FA:{your_email} account. Congratulations! You have successfully logged
                in with Two-factor Authentication enabled!
            </div>
        </div>
    </div>
</div>
