<!-- Include Alert Message here, better than showing it in the layout to more easily control css -->
@include('row-alert')

<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default div-form-top">
            <div class="panel-heading div-form-title">
                Two Factor Authentication Verification
            </div>
            <div class="panel-body">
                {{ Form::open(array('url'=>'users/login-verify', 'class'=>'form-signin', 'role'=>'form')) }}
                <div class="form-group">
                    {{ Form::label('user_otp', '6 digits code generated by Google Authenticator') }}
                    {{ Form::text('user_otp', null, array('class'=>'form-control')) }}
                </div>
                {{ Form::submit('Verify', array('class'=>'btn btn-success btn-block'))}}
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>