{{ Form::open(array('url'=>'users/disable-authenticator', 'role'=>'form')) }}
    <div class="panel panel-default auto-hori-margin">
        <div class="panel-heading setting-panel-heading">
            Two Factor Authentication: On
        </div>
        <div class="panel-body" id="disable-two-factor">
            <div class="instruction-div">
                Enter below the 6 digits code generated by Google Authenticator and click on "Turn Off Two Factor Authentication" button.
            </div>
            <div class="form-group">
                {{ Form::label('user_otp', '6 digits code generated by Google Authenticator') }}
                {{ Form::text('user_otp', null, array('class'=>'form-control')) }}
            </div>
            {{ Form::submit('Turn Off Two Factor Authentication', array('class'=>'btn btn-success btn-block'))}}
        </div>
    </div>
{{ Form::close() }}