{{ Form::open(array('url'=>'users/enable-authenticator', 'role'=>'form')) }}
    <div class="panel panel-default auto-hori-margin">
        <div class="panel-heading setting-panel-heading">
            Two Factor Authentication: Off
        </div>
        <div class="panel-body" id="enable-two-factor">
            <div class="instruction-div">
                Instruction to turn on Two Factor Authentication
            </div>
            <div class="instruction-div">
                STEP 1: Get Google Authenticator -
                {{ HTML::link('https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2', 'Android', array('target'=>'_blank')) . ',' }}
                {{ HTML::link('https://itunes.apple.com/us/app/google-authenticator/id388497605?mt=8', 'iOS', array('target'=>'_blank')) . ',' }}
                {{ HTML::link('http://www.windowsphone.com/en-us/store/app/authenticator/e7994dbc-2336-4950-91ba-ca22d653759b', 'Windows Phone', array('target'=>'_blank')) }}
            </div>
            <div class="instruction-div">
                STEP 2: Scan the QR code below using the app. (Also keep a cold text copy of the secret key just in case.)
                <div class="image-div">
                    <img src="{{ url($qr_link) }}" class="img-thumbnail">
                </div>
                <div>Secret Key: <b>{{ $secret }}</b></div>
            </div>
            <div class="instruction-div">
                STEP 3: Enter below the 6 digits code generated by Google Authenticator and click on "Turn On Two Factor Authentication" button.
            </div>
            <div class="form-group">
                {{ Form::label('user_otp', '6 digits code generated by Google Authenticator') }}
                {{ Form::text('user_otp', null, array('class'=>'form-control')) }}
            </div>
            {{ Form::submit('Turn On Two Factor Authentication', array('class'=>'btn btn-success btn-block'))}}
        </div>
    </div>
{{ Form::close() }}